server:
  port: 8080
  
spring:
  application:
    name: lightsaber-service
  cache:    type: redis
  redis:    host: locahost
    port: 6379
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lightsaberdb
    username: postgres
    password: postgres
    hikari:
      pool-name: lightsaber-service
      maximum-pool-size: 30
      max-lifetime: 1800000
      idle-timeout: 30000
      data-source-properties:
        useServerPrepStmts: true
        cachePrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

ibm:  mq:    queue-manager: QMKINOBI
    channel: DEV.ADMIN.SVRCONN
    conn-name: localhost(1414)
    user: admin
    password: passw0rd
    client-id: ${spring.application.name}
    application-name: ${spring.application.name}
    pool:
      enabled: true
      maxConnections: 5
    
app:
  messaging:
    input: LIGHTSABER.ORDER.QUEUE
    output: LIGHTSABER.CONFIRMATION.QUEUE
    
logging:
  level:
   com:
     ibm:
       mq:
         spring:
           boot: TRACE